### ISSUE TITLE
Responder Mode: Setup Review Model 

### ISSUE THREAD

**Issue by abigail-hampson** [torchbox/m-response#20]

**Comment by tm-kn** [comment]
@abigail-hampson, if you want to have a look, I have added just a very basic admin site setup for the following models to be able to test as a user:

 - Review
 - Application
 - Application version

I'll be following up with the more sophisticated configuration of the admin in #25, so that is just what Django gives us out of the box.

**Comment by abigail-hampson** [comment]
Looks good from what is there. Thanks
